### ISSUE TITLE
SQL Errors

### ISSUE THREAD

**Issue by chrisgwynne** [richardkeep/covid-19#1]
Just trying to run this now.

I get SQL errors?

ErrorException
SQLSTATE[HY000]: General error: 1 near ",": syntax error (SQL: insert into "coronas" ("activeCases", "cases", "country", "critical", "deaths", "id", "recovered", "todayCases", "todayDeaths") values (37860, 47021, Italy, 2655, 4032, 1, 5129, 0, 0), (6013, 81008, China, 1927, 3255, 2, 71740, 41, 7), (11466, 19644, Iran, 0, 1433, 3, 6745, 0, 0), (18890, 21571, Spain, 939, 1093, 4, 1588, 0, 0), (10575, 12612, France, 1297, 450, 5, 1587, 0, 0), (19229, 19640, USA, 64, 264, 6, 147, 257, 8), 

Any ideas?

**Comment by richardkeep** [comment]
Are you still getting the above error?

**Comment by cha7ta** [comment]
yeah we have this probleme is still

**Comment by richardkeep** [comment]
I have removed the Sushi package. The error is gone now. Fork the repo and try again
