### ISSUE TITLE
Full bleed on mobile

### ISSUE THREAD

**Issue by mittelgrau** [richardkeep/covid-19#10]
Adding a full bleed Stats Card view with some small padding to the left would be a small but pleasing visual enhancment for a mobile viewport. Would also act as an indicator that there is more stuff to the right. To stay within the tailwind paradigm you could use this [utility](https://github.com/tack-hammer/tailwind-plugin-full-bleed)
<img width="311" alt="Bildschirmfoto 2020-04-14 um 16 45 55" src="https://user-images.githubusercontent.com/30243035/79238378-9a18af00-7e6f-11ea-9cd1-48e909e7c820.png">

**Comment by richardkeep** [comment]
I'd really appreciate a pull request for this

**Comment by mittelgrau** [comment]
will do! First i need to ask the respository owner of the full bleed utility to add an 'unset' variant for certain Breakpoints.

**Comment by Homezonic** [comment]
@richardkeep is the owner of course @mittelgrau

**Comment by richardkeep** [comment]
> will do! First i need to ask the respository owner of the full bleed utility to add an 'unset' variant for certain Breakpoints.

I am the repo owner. You can go ahead and add it.

**Comment by mittelgrau** [comment]
> > will do! First i need to ask the respository owner of the full bleed utility to add an 'unset' variant for certain Breakpoints.
> 
> 
> 
> I am the repo owner. You can go ahead and add it. 

I think you misread :) i meant the owner of the tailwind utility i wanted to use.

**Comment by richardkeep** [comment]
> > > will do! First i need to ask the respository owner of the full bleed utility to add an 'unset' variant for certain Breakpoints.
> > 
> > 
> > I am the repo owner. You can go ahead and add it.
> 
> I think you misread :) i meant the owner of the tailwind utility i wanted to use.

Ah, I get you. You can fork the repo and add it yourself :)

**Comment by mittelgrau** [comment]
I know, would be the easiest way but then there would be another Npm Package in the world. 😅
