### ISSUE TITLE
SQLSTATE[HY000]: General error: 1 too many SQL variables !!

### ISSUE THREAD

**Issue by rocktohq** [richardkeep/covid-19#3]
**I got this error :/**
ErrorException
SQLSTATE[HY000]: General error: 1 too many SQL variables (SQL: insert into "coronas" ("activeCases", "cases", "country", "critical", "deaths", "id", "recovered", "todayCases", "todayDeaths") values (42681, 53578, Italy, 2857, 4825, 1, 6072, 6557, 793), (6013, 81008, China, 1927, 3255, 2, 71740, 41, 7), (11419, 20610, Iran, 0, 1556, 3, 7635, 966, 123), (21871, 25374, Spain, 1612, 1378, 4, 2125, 3803, 285), (12310, 14459, France, 1525, 562, 5, 1587, 1847, 112), (23683, 24142, USA, 64, 288, 6, 171, 4759, 32), (4692, 5018, UK, 20, 233, 7, 93, 1035, 56), (3493, 3631, Netherlands, 354, 136, 8, 2, 637, 30), (6085, 8799, S. Korea, 59, 102, 9, 2612, 147, 8), (21920, 22213, Germany, 2, 84, 10, 209, 2365, 16), (6575, 6665, Switzerland, 141, 75, 11, 15, 1050, 19), (2485, 2815, Belgium, 288, 67, 12, 263, 558, 30), (392, 450, Indonesia, 0, 38, 13, 20, 81, 6), (795, 1046, Japan, 55, 36, 14, 215, 39, 1), (127, 151, San Marino, 12, 20, 15, 4, 0, 6), (1728, 1764, Sweden, 69, 20, 16, 16, 125, 4), (275, 307, Philippines, 1, 19, 17, 13, 77, 1), (1173, 1205, Canada, 1, 18, 18, 14, 118, 6), (1008, 1028, Brazil, 18, 18, 19, 2, 58, 7), (146, 214, Iraq, 0, 17, 20, 51, 6, 0), (59, 139, Algeria, 0, 15, 21, 65, 45, 4), (498, 530, Greece, 20, 13, 22, 19, 35, 3), (1312, 1326, Denmark, 42, 13, 23, 1, 71, 4), (1263, 1280, Portugal, 26, 12, 24, 5, 260, 6), (242, 294, Egypt, 0, 10, 25, 42, 9, 2), (661, 670, Turkey, 0, 9, 26, 0, 0, 0), (137, 712, Diamond Princess, 15, 8, 27, 567, 0, 0), (656, 670, Luxembourg, 3, 8, 28, 6, 186, 3), (2931, 2948, Austria, 15, 8, 29, 9, 299, 2), (1061, 1183, Malaysia, 26, 8, 30, 114, 153, 5), (1019, 1072, Australia, 2, 7, 31, 46, 144, 0), (2134, 2142, Norway, 28, 7, 32, 1, 183, 0), (496, 506, Ecuador, 2, 7, 33, 3, 80, 0), (312, 318, Peru, 5, 5, 34, 1, 55, 1), (518, 536, Poland, 3, 5, 35, 13, 111, 0), (304, 332, India, 0, 5, 36, 23, 83, 0), (171, 273, Hong Kong, 4, 4, 37, 98, 17, 0), (151, 158, Argentina, 0, 4, 38, 3, 0, 1), (218, 230, Lebanon, 4, 4, 39, 8, 53, 0), (92, 103, Hungary, 6, 4, 40, 7, 18, 0), (43, 47, Ukraine, 0, 3, 41, 1, 6, 0), (157, 163, Bulgaria, 3, 3, 42, 3, 36, 0), (777, 785, Ireland, 6, 3, 43, 5, 102, 0), (90, 96, Morocco, 1, 3, 44, 3, 10, 0), (109, 112, Dominican Republic, 0, 3, 45, 0, 40, 1), (56, 64, Burkina Faso, 0, 3, 46, 5, 24, 2), (718, 734, Pakistan, 0, 3, 47, 13, 233, 0), (113, 117, Costa Rica, 2, 2, 48, 2, 4, 0), (72, 76, Albania, 2, 2, 49, 2, 6, 0), (290, 432, Singapore, 14, 2, 50, 140, 47, 2), (123, 153, Taiwan, 0, 2, 51, 28, 18, 0), (113, 153, UAE, 2, 2, 52, 38, 13, 0), (197, 203, Mexico, 1, 2, 53, 4, 39, 1), (19, 24, Bangladesh, 0, 2, 54, 3, 4, 1), (17, 18, Paraguay, 1, 1, 55, 0, 0, 1), (97, 99, Lithuania, 1, 1, 56, 1, 30, 0), (1, 2, Sudan, 0, 1, 57, 0, 0, 0), (90, 93, Bosnia and Herzegovina, 1, 1, 58, 2, 4, 1), (16, 19, Jamaica, 0, 1, 59, 2, 0, 0), (20, 21, Cuba, 0, 1, 60, 0, 0, 0), (2, 3, Cayman Islands, 0, 1, 61, 0, 0, 0), (78, 80, Moldova, 3, 1, 62, 1, 14, 0), (58, 60, Tunisia, 7, 1, 63, 1, 6, 0), (41, 53, Azerbaijan, 0, 1, 64, 11, 9, 0), (31, 32, Martinique, 7, 1, 65, 0, 0, 0), (50, 51, Guadeloupe, 4, 1, 66, 0, 0, 0), (2, 3, Curaçao, 0, 1, 67, 0, 0, 0), (4, 5, Guyana, 0, 1, 68, 0, 0, 0), (467, 473, Iceland, 1, 1, 69, 5, 64, 1), (184, 310, Bahrain, 4, 1, 70, 125, 12, 0), (13, 14, Mauritius, 0, 1, 71, 0, 2, 1), (168, 171, Serbia, 4, 1, 72, 2, 36, 0), (16, 17, Guatemala, 0, 1, 73, 0, 5, 0), (198, 200, Panama, 7, 1, 74, 1, 0, 0), (846, 883, Israel, 15, 1, 75, 36, 178, 0), (200, 206, Croatia, 0, 1, 76, 5, 76, 0), (382, 383, Slovenia, 12, 1, 77, 0, 42, 0), (366, 411, Thailand, 7, 1, 78, 44, 89, 0), (512, 523, Finland, 2, 1, 79, 10, 73, 1), (3, 4, Gabon, 0, 1, 80, 0, 0, 0), (289, 306, Russia, 0, 1, 81, 16, 53, 0), (7, 7, Seychelles, 0, 0, 82, 0, 0, 0), (4, 4, Bahamas, 0, 0, 83, 0, 0, 0), (3, 3, Congo, 0, 0, 84, 0, 0, 0), (7, 7, Mayotte, 0, 0, 85, 0, 0, 0), (7, 7, Kenya, 0, 0, 86, 0, 0, 0), (3, 3, Liberia, 0, 0, 87, 0, 1, 0), (3, 3, El Salvador, 0, 0, 88, 0, 2, 0), (6, 6, Barbados, 0, 0, 89, 0, 0, 0), (3, 3, CAR, 0, 0, 90, 0, 0, 0), (3, 3, Cabo Verde, 0, 0, 91, 0, 2, 0), (4, 4, Suriname, 0, 0, 92, 0, 0, 0), (6, 6, Equatorial Guinea, 0, 0, 93, 0, 0, 0), (6, 6, Tanzania, 0, 0, 94, 0, 0, 0), (4, 4, Saint Martin, 0, 0, 95, 0, 0, 0), (4, 4, New Caledonia, 0, 0, 96, 0, 2, 0), (6, 6, U.S. Virgin Islands, 0, 0, 97, 0, 3, 0), (4, 5, Aruba, 0, 0, 98, 1, 0, 0), (3, 3, Madagascar, 0, 0, 99, 0, 0, 0), (0, 1, Nepal, 0, 0, 100, 1, 0, 0), (3, 3, Namibia, 0, 0, 101, 0, 0, 0), (1, 1, Antigua and Barbuda, 0, 0, 102, 0, 0, 0), (1, 1, Eswatini, 0, 0, 103, 0, 0, 0), (1, 1, Somalia, 0, 0, 104, 0, 0, 0), (1, 1, Sint Maarten, 0, 0, 105, 0, 0, 0), (1, 1, St. Vincent Grenadines, 0, 0, 106, 0, 0, 0), (1, 1, Papua New Guinea, 0, 0, 107, 0, 0, 0), (1, 1, Niger, 0, 0, 108, 0, 0, 0), (1, 1, Montserrat, 0, 0, 109, 0, 0, 0), (1, 1, Vatican City, 0, 0, 110, 0, 0, 0), (1, 1, Gambia, 0, 0, 111, 0, 0, 0), (1, 1, Eritrea, 0, 0, 112, 0, 1, 0), (1, 1, Djibouti, 0, 0, 113, 0, 0, 0), (10, 10, Mongolia, 0, 0, 114, 0, 4, 0), (1, 1, Chad, 0, 0, 115, 0, 0, 0), (2, 2, Zambia, 0, 0, 116, 0, 0, 0), (3, 3, St. Barth, 0, 0, 117, 0, 0, 0), (2, 2, Saint Lucia, 0, 0, 118, 0, 0, 0), (2, 2, Nicaragua, 0, 0, 119, 0, 0, 0), (2, 2, Mauritania, 0, 0, 120, 0, 0, 0), (2, 2, Isle of Man, 0, 0, 121, 0, 0, 0), (2, 2, Haiti, 0, 0, 122, 0, 0, 0), (2, 2, Guinea, 0, 0, 123, 0, 0, 0), (2, 2, Greenland, 0, 0, 124, 0, 0, 0), (2, 2, Fiji, 0, 0, 125, 0, 1, 0), (2, 2, Bhutan, 0, 0, 126, 0, 0, 0), (2, 2, Bermuda, 0, 0, 127, 0, 0, 0), (2, 2, Benin, 0, 0, 128, 0, 0, 0), (2, 2, Angola, 0, 0, 129, 0, 1, 0), (3, 3, Zimbabwe, 0, 0, 130, 0, 2, 0), (9, 9, Ethiopia, 0, 0, 131, 0, 0, 0), (39, 52, Oman, 0, 0, 132, 13, 4, 0), (8, 10, Gibraltar, 0, 0, 133, 2, 0, 0), (110, 110, Uruguay, 0, 0, 134, 0, 0, 0), (55, 70, Venezuela, 2, 0, 135, 15, 5, 0), (71, 73, Malta, 1, 0, 136, 2, 9, 0), (61, 76, Belarus, 0, 0, 137, 15, 7, 0), (74, 77, Sri Lanka, 2, 0, 138, 3, 4, 0), (82, 83, Brunei, 2, 0, 139, 1, 5, 0), (84, 84, Cyprus, 1, 0, 140, 0, 9, 0), (84, 85, North Macedonia, 1, 0, 141, 1, 9, 0), (87, 88, Andorra, 2, 0, 142, 1, 13, 0), (89, 92, Faeroe Islands, 0, 0, 143, 3, 12, 0), (77, 94, Vietnam, 2, 0, 144, 17, 3, 0), (98, 99, Jordan, 0, 0, 145, 1, 15, 0), (123, 124, Latvia, 0, 0, 146, 1, 13, 0), (53, 53, Kazakhstan, 0, 0, 147, 0, 1, 0), (159, 160, Armenia, 2, 0, 148, 1, 24, 0), (149, 176, Kuwait, 5, 0, 149, 27, 17, 0), (171, 178, Slovakia, 2, 0, 150, 7, 41, 0), (195, 196, Colombia, 0, 0, 151, 1, 51, 0), (238, 240, South Africa, 0, 0, 152, 2, 38, 0), (304, 306, Estonia, 1, 0, 153, 2, 23, 0), (315, 367, Romania, 14, 0, 154, 52, 59, 0), (376, 392, Saudi Arabia, 0, 0, 155, 16, 48, 0), (454, 481, Qatar, 6, 0, 156, 27, 11, 0), (529, 537, Chile, 7, 0, 157, 8, 103, 0), (989, 995, Czechia, 7, 0, 158, 6, 162, 0), (51, 53, Cambodia, 0, 0, 159, 2, 2, 0), (52, 52, New Zealand, 0, 0, 160, 0, 0, 0), (10, 13, Maldives, 0, 0, 161, 3, 0, 0), (19, 19, Ghana, 0, 0, 162, 0, 3, 0), (14, 14, Montenegro, 0, 0, 163, 0, 0, 0), (14, 14, Kyrgyzstan, 0, 0, 164, 0, 8, 0), (13, 14, Ivory Coast, 0, 0, 165, 1, 5, 0), (15, 15, Guam, 0, 0, 166, 0, 1, 0), (15, 15, French Polynesia, 0, 0, 167, 0, 4, 0), (16, 16, Togo, 0, 0, 168, 0, 7, 0), (17, 17, Rwanda, 0, 0, 169, 0, 0, 0), (17, 17, Puerto Rico, 0, 0, 170, 0, 3, 0), (18, 18, French Guiana, 0, 0, 171, 0, 3, 0), (17, 18, Monaco, 0, 0, 172, 1, 7, 0), (8, 18, Macao, 0, 0, 173, 10, 1, 0), (19, 19, Bolivia, 0, 0, 174, 0, 3, 0), (35, 52, Palestine, 0, 0, 175, 17, 4, 0), (21, 22, Nigeria, 0, 0, 176, 1, 10, 0), (23, 23, DRC, 0, 0, 177, 0, 5, 0), (24, 24, Honduras, 0, 0, 178, 0, 0, 0), (23, 24, Afghanistan, 0, 0, 179, 1, 0, 0), (25, 27, Cameroon, 0, 0, 180, 2, 0, 0), (32, 32, Channel Islands, 0, 0, 181, 0, 20, 0), (37, 37, Liechtenstein, 0, 0, 182, 0, 9, 0), (41, 41, Uzbekistan, 0, 0, 183, 0, 8, 0), (45, 45, Réunion, 0, 0, 184, 0, 7, 0), (42, 47, Senegal, 0, 0, 185, 5, 0, 0), (49, 49, Trinidad and Tobago, 0, 0, 186, 0, 40, 0), (48, 49, Georgia, 1, 0, 187, 1, 5, 0), (1, 1, Timor-Leste, 0, 0, 188, 0, 1, 0)) (View: C:\xampp\htdocs\covid\resources\views\corona.blade.php)

**Comment by richardkeep** [comment]
This issue has already been reported [here](https://github.com/calebporzio/sushi/issues/56), let's wait and see what the creator of the Sushi package will solve it.

**Comment by richardkeep** [comment]
I have removed the Sushi package. The error is gone now. Fork the repo and try again
