### ISSUE TITLE
ErrorException SQLSTATE[HY000]: General error: 1 too many SQL variables

### ISSUE THREAD

**Issue by Binuanand** [richardkeep/covid-19#5]
ErrorException
SQLSTATE[HY000]: General error: 1 too many SQL variables (SQL: insert into "coronas" ("activeCases", "cases", "country", "critical", "deaths", "id", "recovered", "todayCases", "todayDeaths") values (54030, 69176, Italy, 3393, 6820, 1, 8326, 0, 0), (4287, 81218, China, 1399, 3281, 2, 73650, 47, 4), (35273, 42058, Spain, 2636, 2991, 3, 3794, 0, 0), (13964, 24811, Iran, 0, 1934, 4, 8913, 0, 0), (17923, 22304, France, 2516, 1100, 5, 3281, 0, 0), (53778, 54941, USA, 1175, 784, 6, 379, 60, 4), (7520, 8077, UK, 20, 422, 7, 135, 0, 0), (5282, 5560, Netherlands, 435, 276, 8, 2, 0, 0), (30482, 33952, Germany, 23, 171, 9, 3299, 961, 12), (9905, 10171, Switzerland, 141, 135, 10, 131, 294, 13), (5281, 9137, S. Korea, 59, 126, 11, 3730, 100, 6), (3686, 4269, Belgium, 381, 122, 12, 461, 0, 0), (701, 790, Indonesia, 0, 58, 13, 31, 104, 3), (2199, 2247, Brazil, 18, 46, 14, 2, 0, 0), (1828, 1872, Turkey, 0, 44, 15, 0, 0, 0), (865, 1193, Japan, 54, 43, 16, 285, 0, 0), (2244, 2300, Sweden, 144, 40, 17, 16, 1, 0), (572, 636, Philippines, 1, 38, 18, 26, 84, 3), (2307, 2362, Portugal, 48, 33, 19, 22, 0, 0), (1682, 1715, Denmark, 69, 32, 20, 1, 124, 0), (5446, 5485, Austria, 26, 30, 21, 9, 202, 2), (1052, 1082, Ecuador, 2, 27, 22, 3, 0, 0), (214, 316, Iraq, 0, 27, 23, 75, 0, 0), (2654, 2792, Canada, 1, 26, 24, 112, 0, 0), (162, 187, San Marino, 12, 21, 25, 4, 0, 0), (694, 743, Greece, 35, 20, 26, 29, 0, 0), (302, 402, Egypt, 0, 20, 27, 80, 0, 0), (180, 264, Algeria, 0, 19, 28, 65, 0, 0), (1578, 1796, Malaysia, 64, 19, 29, 199, 172, 3), (702, 794, Romania, 15, 13, 30, 79, 0, 1), (2849, 2868, Norway, 44, 13, 31, 6, 2, 1), (914, 927, Poland, 3, 12, 32, 1, 26, 2), (512, 562, India, 0, 10, 33, 40, 26, 0), (195, 226, Hungary, 6, 10, 34, 21, 39, 1), (115, 712, Diamond Princess, 15, 10, 35, 587, 0, 0), (2297, 2423, Australia, 11, 8, 36, 118, 106, 0), (1085, 1099, Luxembourg, 3, 8, 37, 6, 0, 0), (974, 1000, Pakistan, 5, 7, 38, 19, 28, 0), (408, 416, Peru, 9, 7, 39, 1, 0, 0), (1317, 1329, Ireland, 29, 7, 40, 5, 0, 0), (329, 387, Argentina, 0, 6, 41, 52, 0, 0), (303, 312, Dominican Republic, 0, 6, 42, 3, 0, 0), (436, 443, Panama, 33, 6, 43, 1, 0, 0), (1967, 2030, Israel, 37, 5, 44, 58, 100, 2), (27, 39, Bangladesh, 0, 5, 45, 7, 0, 1), (159, 170, Morocco, 1, 5, 46, 6, 0, 0), (396, 405, Mexico, 1, 5, 47, 4, 38, 1), (108, 123, Albania, 2, 5, 48, 10, 0, 0), (473, 480, Slovenia, 12, 4, 49, 3, 0, 0), (108, 113, Ukraine, 0, 4, 50, 1, 11, 1), (109, 114, Tunisia, 11, 4, 51, 1, 0, 0), (103, 114, Burkina Faso, 0, 4, 52, 7, 0, 0), (860, 934, Thailand, 11, 4, 53, 70, 107, 0), (281, 387, Hong Kong, 4, 4, 54, 102, 0, 0), (284, 303, Serbia, 21, 4, 55, 15, 0, 1), (306, 318, Lebanon, 4, 4, 56, 8, 0, 0), (34, 37, Paraguay, 1, 3, 57, 0, 10, 1), (213, 220, Bulgaria, 8, 3, 58, 4, 2, 0), (1484, 1497, Czechia, 19, 3, 59, 10, 103, 0), (163, 168, Bosnia and Herzegovina, 1, 3, 60, 2, 0, 0), (251, 255, Lithuania, 1, 3, 61, 1, 46, 1), (828, 841, Finland, 11, 3, 62, 10, 49, 2), (118, 124, Cyprus, 3, 3, 63, 3, 0, 0), (369, 378, Colombia, 0, 3, 64, 6, 0, 0), (212, 392, Bahrain, 2, 3, 65, 177, 0, 0), (46, 48, Mauritius, 1, 2, 66, 0, 6, 0), (145, 148, North Macedonia, 1, 2, 67, 1, 0, 0), (43, 45, DRC, 0, 2, 68, 0, 0, 0), (51, 53, Ghana, 0, 2, 69, 0, 0, 0), (71, 74, Afghanistan, 0, 2, 70, 1, 0, 1), (173, 177, Costa Rica, 4, 2, 71, 2, 0, 0), (400, 558, Singapore, 17, 2, 72, 156, 0, 0), (903, 922, Chile, 7, 2, 73, 17, 0, 0), (204, 235, Taiwan, 0, 2, 74, 29, 19, 0), (201, 248, UAE, 2, 2, 75, 45, 0, 0), (595, 648, Iceland, 13, 2, 76, 51, 0, 0), (5, 6, Curaçao, 0, 1, 77, 0, 0, 0), (76, 87, Azerbaijan, 6, 1, 78, 10, 0, 0), (72, 73, Guadeloupe, 4, 1, 79, 0, 0, 0), (63, 66, Cameroon, 0, 1, 80, 2, 0, 0), (56, 57, Martinique, 7, 1, 81, 0, 0, 0), (5, 6, Gabon, 0, 1, 82, 0, 0, 0), (22, 25, Jamaica, 0, 1, 83, 2, 4, 0), (2, 3, Zimbabwe, 0, 1, 84, 0, 0, 0), (5, 6, Cayman Islands, 0, 1, 85, 0, 0, 0), (2, 3, Sudan, 0, 1, 86, 0, 0, 0), (51, 52, Montenegro, 0, 1, 87, 0, 5, 0), (2, 3, Cabo Verde, 0, 1, 88, 0, 0, 0), (46, 48, Cuba, 2, 1, 89, 1, 0, 0), (43, 46, Nigeria, 0, 1, 90, 2, 2, 0), (2, 3, Gambia, 0, 1, 91, 0, 0, 0), (20, 21, Guatemala, 0, 1, 92, 0, 0, 0), (4, 5, Guyana, 0, 1, 93, 0, 0, 0), (6, 7, Niger, 0, 1, 94, 0, 4, 1), (401, 418, Croatia, 6, 1, 95, 16, 36, 0), (162, 164, Andorra, 7, 1, 96, 1, 0, 0), (738, 767, Saudi Arabia, 0, 1, 97, 28, 0, 0), (628, 658, Russia, 8, 1, 98, 29, 163, 0), (122, 125, Moldova, 20, 1, 99, 2, 0, 0), (3, 3, Myanmar, 0, 0, 100, 0, 0, 0), (4, 4, Vatican City, 0, 0, 101, 0, 0, 0), (4, 4, Guinea, 0, 0, 102, 0, 0, 0), (1, 1, Somalia, 0, 0, 103, 0, 0, 0), (4, 4, Congo, 0, 0, 104, 0, 0, 0), (3, 5, Greenland, 0, 0, 105, 2, 0, 0), (5, 5, Fiji, 0, 0, 106, 0, 1, 0), (4, 5, Bahamas, 0, 0, 107, 1, 0, 0), (1, 1, Syria, 0, 0, 108, 0, 0, 0), (1, 1, St. Vincent Grenadines, 0, 0, 109, 0, 0, 0), (6, 6, Bermuda, 0, 0, 110, 0, 0, 0), (6, 6, Benin, 0, 0, 111, 0, 0, 0), (1, 1, Timor-Leste, 0, 0, 112, 0, 0, 0), (7, 7, Suriname, 0, 0, 113, 0, 0, 0), (7, 7, Seychelles, 0, 0, 114, 0, 0, 0), (5, 7, Namibia, 0, 0, 115, 2, 0, 0), (7, 7, Haiti, 0, 0, 116, 0, 0, 0), (7, 7, Dominica, 0, 0, 117, 0, 0, 0), (4, 4, Eswatini, 0, 0, 118, 0, 0, 0), (1, 1, Montserrat, 0, 0, 119, 0, 0, 0), (1, 1, Papua New Guinea, 0, 0, 120, 0, 0, 0), (2, 2, Laos, 0, 0, 121, 0, 0, 0), (3, 3, Liberia, 0, 0, 122, 0, 0, 0), (3, 3, St. Barth, 0, 0, 123, 0, 0, 0), (3, 3, Saint Lucia, 0, 0, 124, 0, 0, 0), (3, 3, Zambia, 0, 0, 125, 0, 0, 0), (3, 3, Djibouti, 0, 0, 126, 0, 0, 0), (3, 3, Chad, 0, 0, 127, 0, 0, 0), (2, 2, Bhutan, 0, 0, 128, 0, 0, 0), (3, 3, CAR, 0, 0, 129, 0, 0, 0), (3, 3, Antigua and Barbuda, 0, 0, 130, 0, 0, 0), (3, 3, Mozambique, 0, 0, 131, 0, 0, 0), (3, 3, Angola, 0, 0, 132, 0, 0, 0), (2, 2, Mauritania, 0, 0, 133, 0, 0, 0), (2, 3, Nepal, 0, 0, 134, 1, 1, 0), (2, 2, Nicaragua, 0, 0, 135, 0, 0, 0), (2, 2, Sint Maarten, 0, 0, 136, 0, 0, 0), (1, 1, Belize, 0, 0, 137, 0, 0, 0), (1, 1, Eritrea, 0, 0, 138, 0, 0, 0), (8, 8, Saint Martin, 0, 0, 139, 0, 0, 0), (1, 1, Libya, 0, 0, 140, 0, 0, 0), (1, 1, Grenada, 0, 0, 141, 0, 0, 0), (79, 79, Kazakhstan, 0, 0, 142, 0, 7, 0), (9, 9, Uganda, 0, 0, 143, 0, 0, 0), (108, 110, Malta, 1, 0, 144, 2, 0, 0), (71, 73, Ivory Coast, 0, 0, 145, 2, 0, 0), (63, 73, Georgia, 1, 0, 146, 10, 3, 0), (78, 86, Senegal, 0, 0, 147, 8, 0, 0), (57, 86, Belarus, 2, 0, 148, 29, 5, 0), (76, 91, Venezuela, 2, 0, 149, 15, 7, 0), (89, 93, Cambodia, 1, 0, 150, 4, 2, 0), (93, 94, Réunion, 0, 0, 151, 1, 0, 0), (82, 99, Oman, 0, 0, 152, 17, 15, 0), (99, 102, Sri Lanka, 2, 0, 153, 3, 0, 0), (107, 109, Brunei, 1, 0, 154, 2, 5, 0), (94, 132, Faeroe Islands, 2, 0, 155, 38, 10, 0), (57, 57, Trinidad and Tobago, 0, 0, 156, 0, 0, 0), (117, 134, Vietnam, 3, 0, 157, 17, 0, 0), (153, 154, Jordan, 0, 0, 158, 1, 0, 0), (189, 189, Uruguay, 3, 0, 159, 0, 0, 0), (152, 195, Kuwait, 6, 0, 160, 43, 4, 0), (183, 205, New Zealand, 0, 0, 161, 22, 0, 0), (209, 216, Slovakia, 2, 0, 162, 7, 12, 0), (220, 221, Latvia, 0, 0, 163, 1, 24, 0), (249, 265, Armenia, 6, 0, 164, 16, 16, 0), (396, 404, Estonia, 5, 0, 165, 8, 35, 0), (485, 526, Qatar, 6, 0, 166, 41, 0, 0), (705, 709, South Africa, 2, 0, 167, 4, 155, 0), (46, 62, Palestine, 0, 0, 168, 16, 2, 0), (55, 55, Uzbekistan, 4, 0, 169, 0, 5, 0), (9, 9, Equatorial Guinea, 0, 0, 170, 0, 0, 0), (19, 20, Togo, 0, 0, 171, 1, 0, 0), (9, 9, El Salvador, 0, 0, 172, 0, 4, 0), (10, 10, Mongolia, 0, 0, 173, 0, 0, 0), (12, 12, Tanzania, 0, 0, 174, 0, 0, 0), (12, 12, Ethiopia, 0, 0, 175, 0, 0, 0), (8, 13, Maldives, 0, 0, 176, 5, 0, 0), (14, 14, New Caledonia, 0, 0, 177, 0, 4, 0), (10, 15, Gibraltar, 0, 0, 178, 5, 0, 0), (16, 17, Aruba, 0, 0, 179, 1, 0, 0), (18, 18, Barbados, 0, 0, 180, 0, 0, 0), (19, 19, Madagascar, 0, 0, 181, 0, 2, 0), (23, 23, Isle of Man, 0, 0, 182, 0, 0, 0), (51, 51, Liechtenstein, 0, 0, 183, 0, 0, 0), (17, 23, French Guiana, 0, 0, 184, 6, 0, 0), (22, 23, Monaco, 0, 0, 185, 1, 0, 0), (25, 25, Kenya, 0, 0, 186, 0, 0, 0), (25, 25, French Polynesia, 0, 0, 187, 0, 0, 0), (20, 30, Macao, 0, 0, 188, 10, 1, 0), (32, 32, Bolivia, 0, 0, 189, 0, 3, 0), (36, 36, Mayotte, 0, 0, 190, 0, 0, 0), (36, 36, Honduras, 0, 0, 191, 0, 6, 0), (36, 36, Channel Islands, 0, 0, 192, 0, 0, 0), (40, 40, Rwanda, 0, 0, 193, 0, 0, 0), (44, 44, Kyrgyzstan, 0, 0, 194, 0, 2, 0), (1, 1, Turks and Caicos, 0, 0, 195, 0, 0, 0)) (View: covid-19\resources\views\corona.blade.php)

**Comment by Homezonic** [comment]
Same issue here, but when i copied out only details upto 20, i wont get the error.

**Comment by richardkeep** [comment]
This issue has already been reported [here](https://github.com/calebporzio/sushi/issues/56), let's wait and see what the creator of the Sushi package will solve it.

**Comment by richardkeep** [comment]
I have removed the Sushi package. The error is gone now. Fork the repo and try again
