### ISSUE TITLE
500 internal error

### ISSUE THREAD

**Issue by saikatkoley** [richardkeep/covid-19#6]
after doing all step in this step "php artisan server" this error is showing

Command "server" is not defined.  
                                    
  Did you mean one of these?        
      make:observer                 
      serve    

But when i used serve or php -S localhost:8080 -t public/ 

it showing 500 internal error

**Comment by Homezonic** [comment]
@saikatkoley  Use the following command

`php artisan serve`

**Comment by saikatkoley** [comment]
> @richardkeep Use the following command
> 
> `php artisan serve`

still didn't work.

**Comment by Homezonic** [comment]
@saikatkoley are you using vcode? do you have php components installed?

**Comment by saikatkoley** [comment]
> @saikatkoley are you using vcode? do you have php components installed?

yes i have run composer install and for editing using sublime text editor

**Comment by Homezonic** [comment]
can i see a screenshot?
you on skype?

**Comment by saikatkoley** [comment]
> can i see a screenshot?
> you on skype?

![StaticShot_29-03-2020_22-09-50](https://user-images.githubusercontent.com/20451180/77854859-66504f00-720a-11ea-981c-001f659f1142.png)

**Comment by richardkeep** [comment]
Ensure you have .env file and the storage directory is writable.

**Comment by Homezonic** [comment]
all done and same problem, i also change debugging to true and i was able to know it was error from sql parsing

**Comment by richardkeep** [comment]
I have removed the Sushi package. The error is gone now. Fork the repo and try again

**Comment by saikatkoley** [comment]
now design is not coming properly. ant help?
![StaticShot_04-04-2020_20-39-23](https://user-images.githubusercontent.com/20451180/78454274-ac972980-76b4-11ea-9a2f-4cbc984fdb5e.png)

**Comment by richardkeep** [comment]
Apply some CSS styles

**Comment by saikatkoley** [comment]
But how can i get the this original design?
