### ISSUE TITLE
Great application

### ISSUE THREAD

**Issue by cha7ta** [richardkeep/covid-19#8]
Hello dearis great application but we can't run it for this error :
ErrorException
SQLSTATE[HY000]: General error: 1 too many SQL variables (SQL: insert into "coronas" ("activeCases", "cases", "country", "critical", "deaths", "emoji", "id", "recovered", "todayCases", "todayDeaths") values ...............

can you fix it?

**Comment by richardkeep** [comment]
I have removed the Sushi package. The error is gone now. Fork the repo and try again
